### PR TITLE
[WIP] add new output formats

### PR DESCRIPTION
**Pull request by mutlusun**
Hello,

this is a first PR to add new output formats. Do not merge, as it is not ready yet. This branch is on top of the modularization branch. There are some small improvements to the module system as well but I didn't want to make the modularization PR even bigger.

Best

### CODE REVIEW

**Comment by mutlusun** [comment]
Dear @pajowu ,
I think this PR lays the basics for multiple output formats and adds a rudimentary CSV output. What do you think is easier? Merging now just the basic stuff or later with more elaborated output formats?
Best

**Comment by pajowu** [comment]
I think we can merge this as soon as #25 is ready (sorry for the delay on that PR again). Look great!

**Comment by mutlusun** [comment]
Again, thanks for your feedback!

In this branch, I have added a CLI argument to use the in memory sqlite connection. The in memory sqlite database had only a small impact on memory usage on my computer/with my backup file. However, I have been unsure whether this is always the case and the default is now the slow and immediate write to the file. 

Do you propose to change the default to in memory databases? I don't have a strong opinion on this ...

**Comment by pajowu** [comment]
I would default to using the in memory db, as it's much faster in my tests and even on big signal backups (I'm testing with about 6 GB backup files), the database section is always under 100mb in size

**Comment by mutlusun** [comment]
I default now to an in memory db. Additionally, I switched back to the openssl crate and it is indeed much faster. Thus, I think this PR is ready to merge.

**Comment by pajowu** [comment]
Great, I will take a last look and then merge it in the next days. Do you have time to resolve the conflicts?

**Comment by mutlusun** [comment]
Done!

**Pull request merged**
